#!/usr/bin/env python3
"""
UserPromptSubmit hook to set session title with launcher prefix + auto-generated name.

This hook runs after the first user prompt is submitted, and sets the session title
to: "<launcher-emoji> <model-alias> <auto-generated-title>"

The auto-generated title is what Claude Code would normally assign based on the
conversation context. We read the current title (which will be the auto-generated
one after the first prompt) and prepend our prefix.

Environment variables (set by launchers):
- LA_SESSION_KIND_EMOJI: The emoji for the session kind (🦾, 📡, ☁️)
- MODEL_ALIAS: The model alias (e.g., nvidia/nemotron-3-ultra-550b-a55b)
- LA_SESSION_IDENTITY: Full session identity JSON
"""

import json
import os
import sys
from pathlib import Path


def log(msg):
    """Log to stderr for debugging."""
    print(f"[session-title-prefix-hook] {msg}", file=sys.stderr)


def get_prefix():
    """Get the session title prefix from environment.

    Uses MODEL_ALIAS (shorter alias like 'nvidia-nemotron-ultra') as primary
    so there's more room for the auto-generated title suffix.
    """
    emoji = os.environ.get("LA_SESSION_KIND_EMOJI", "")
    model_alias = os.environ.get("MODEL_ALIAS", "")
    if emoji and model_alias:
        return f"{emoji} {model_alias}"
    elif emoji:
        return emoji
    elif model_alias:
        return model_alias
    return ""


def get_session_file(session_id):
    """Find the session metadata file for a session ID."""
    sessions_dir = Path.home() / ".claude" / "sessions"
    for session_file in sessions_dir.glob("*.json"):
        try:
            with open(session_file) as f:
                data = json.load(f)
                if data.get("sessionId") == session_id:
                    return session_file
        except Exception:
            continue
    return None


def print_help():
    """Print help message."""
    print("session-title-prefix.py - UserPromptSubmit hook to set session title with launcher prefix")
    print()
    print("Usage:")
    print("  python3 session-title-prefix.py")
    print()
    print("This hook runs after the first user prompt and sets the session title to:")
    print("  <emoji> <model-alias> <auto-generated-title>")
    print()
    print("Environment variables (set by launchers):")
    print("  LA_SESSION_KIND_EMOJI - Emoji for session kind (🦾, 📡, ☁️)")
    print("  MODEL_ALIAS           - Model alias (e.g., nvidia/nemotron-3-ultra-550b-a55b)")
    print("  LA_SESSION_IDENTITY   - Full session identity JSON")
    print()
    print("Input (stdin JSON):")
    print("  session_id - The Claude Code session ID")
    print("  cwd        - Current working directory")
    print()
    print("Output (stdout JSON):")
    print("  hookSpecificOutput.sessionTitle - The new session title")
    print()
    print("Exit codes:")
    print("  0 - Success (including skipped/idempotent)")
    print("  1 - Error")


def main():
    # Check for --help
    if len(sys.argv) > 1 and sys.argv[1] in ("-h", "--help"):
        print_help()
        return 0

    # Read hook input from stdin
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        log(f"Failed to parse stdin JSON: {e}")
        return 0

    # Get session ID
    session_id = input_data.get("session_id", "")
    if not session_id:
        log("No session_id in hook input")
        return 0
    
    # Get the prefix
    prefix = get_prefix()
    if not prefix:
        log("No prefix configured (missing LA_SESSION_KIND_EMOJI or MODEL_ALIAS)")
        return 0
    
    # Get the current session file
    session_file = get_session_file(session_id)
    if not session_file:
        log(f"Could not find session file for ID: {session_id}")
        return 0
    
    # Read current session name
    try:
        with open(session_file) as f:
            session_data = json.load(f)
    except Exception as e:
        log(f"Error reading session file: {e}")
        return 0
    
    current_name = session_data.get("name", "")
    
    # Check if we've already applied the EXACT current prefix (idempotent)
    if current_name.startswith(prefix + " "):
        log("Prefix already applied, skipping")
        return 0

    # Check if the name has a DIFFERENT launcher emoji prefix (e.g., different model on resume)
    # In this case, we SHOULD update to the current prefix - extract auto-generated part
    for emoji in ["🦾", "📡", "☁️", "❓"]:
        if current_name.startswith(emoji + " "):
            # Has a launcher prefix, but it's different from current - REPLACE it
            # Format is "<emoji> <model-alias> <auto-generated>"
            # Split and take everything from the 3rd word as auto-generated
            parts = current_name.split(" ", 2)
            if len(parts) >= 3:
                current_name = parts[2]  # Just the auto-generated part
            elif len(parts) == 2:
                current_name = ""  # Only emoji + model, no auto-generated part
            else:
                current_name = ""
            log(f"Replacing existing launcher prefix with current: {prefix}")
            break
    
    # The current name should be the auto-generated one from Claude Code
    # Prepend our prefix
    new_name = f"{prefix} {current_name}" if current_name else prefix
    
    # Return hookSpecificOutput to set the session title
    # This is the mechanism from the changelog: UserPromptSubmit hooks can set sessionTitle
    output = {
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "sessionTitle": new_name
        }
    }
    
    print(json.dumps(output))
    log(f"Set session title to: {new_name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
